import React, {Component} from 'react';
import {Text, View} from 'react-native';
import ReactNativeAN from 'react-native-alarm-notification';
import {Button} from 'native-base';
import uuid from 'uuid/v1';

import PushNotification from 'react-native-push-notification';

class Remainder extends Component {
  constructor(props) {
    super(props);
    this.state = {
      title: 'Medicine',
      message: 'Berlin-1,hokey-2, refreshed',
      allIds: [],
    };
  }

  setAlarm = () => {
    let id = 1;
    while (this.state.allIds.indexOf(id) !== -1) {
      id += 1;
    }
    PushNotification.localNotificationSchedule({
      /* Android Only Properties */
      id: id, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: 'My Notification Ticker', // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      // bigText: 'now', // (optional) default: "message" prop
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: 'group', // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification
      priority: 'high', // (optional) set notification priority, default: high
      visibility: 'public', // (optional) set notification visibility, default: private
      importance: 'high', // (optional) set notification importance, default: high
      // userInfo: {id},
      /* iOS and Android properties */
      title: 'Remainder for Medicine', // (optional)
      message: 'evening three', // (required)
      date: new Date(Date.now() + 2000),
      playSound: false, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      // repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
      // actions: '["Yes", "No"]', // (Android only) See the doc for notification actions to know more
    });
    let allIds = this.state.allIds;
    allIds.push(id);
    this.setState({allIds});
    PushNotification.cancelLocalNotifications({id});
    alert(id);
  };

  render() {
    return (
      <View>
        <Button onPress={() => this.setAlarm()}>
          <Text>Set Alarm</Text>
        </Button>
      </View>
    );
  }
}

export default Remainder;
